//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N_m3u8DL_CLI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N_m3u8DL_CLI.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二进制合并...请耐心等待.
        /// </summary>
        public static string binaryMergingPleaseWait {
            get {
                return ResourceManager.GetString("binaryMergingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在判断尾分片是否有效....
        /// </summary>
        public static string checkingLast {
            get {
                return ResourceManager.GetString("checkingLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已关闭完整性检查.
        /// </summary>
        public static string disableIntegrityCheck {
            get {
                return ResourceManager.GetString("disableIntegrityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 杜比视界内容，使用二进制合并...请耐心等待.
        /// </summary>
        public static string dolbyVisionContentMerging {
            get {
                return ResourceManager.GetString("dolbyVisionContentMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已下载完毕.
        /// </summary>
        public static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成数量 .
        /// </summary>
        public static string downloadedCount {
            get {
                return ResourceManager.GetString("downloadedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载失败, 程序退出.
        /// </summary>
        public static string downloadFailed {
            get {
                return ResourceManager.GetString("downloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始下载外挂音频....
        /// </summary>
        public static string downloadingExternalAudioTrack {
            get {
                return ResourceManager.GetString("downloadingExternalAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始下载外挂字幕....
        /// </summary>
        public static string downloadingExternalSubtitleTrack {
            get {
                return ResourceManager.GetString("downloadingExternalSubtitleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载首分片....
        /// </summary>
        public static string downloadingFirstSegement {
            get {
                return ResourceManager.GetString("downloadingFirstSegement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取m3u8内容.
        /// </summary>
        public static string downloadingM3u8 {
            get {
                return ResourceManager.GetString("downloadingM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取m3u8 key....
        /// </summary>
        public static string downloadingM3u8Key {
            get {
                return ResourceManager.GetString("downloadingM3u8Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载MAP文件....
        /// </summary>
        public static string downloadingMapFile {
            get {
                return ResourceManager.GetString("downloadingMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制退出: Ctrl+C.
        /// </summary>
        public static string ExitedCtrlC {
            get {
                return ResourceManager.GetString("ExitedCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强制退出: 强制.
        /// </summary>
        public static string ExitedForce {
            get {
                return ResourceManager.GetString("ExitedForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果输出至 [ffreport.log].
        /// </summary>
        public static string ffmpegDone {
            get {
                return ResourceManager.GetString("ffmpegDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在PATH和程序路径下找不到 ffmpeg.
        /// </summary>
        public static string ffmpegLost {
            get {
                return ResourceManager.GetString("ffmpegLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用ffmpeg合并...请耐心等待.
        /// </summary>
        public static string ffmpegMergingPleaseWait {
            get {
                return ResourceManager.GetString("ffmpegMergingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请下载ffmpeg.exe并把他放到程序同目录..
        /// </summary>
        public static string ffmpegTip {
            get {
                return ResourceManager.GetString("ffmpegTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件时长：.
        /// </summary>
        public static string fileDuration {
            get {
                return ResourceManager.GetString("fileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名称：.
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别到外挂音频轨道.
        /// </summary>
        public static string hasExternalAudioTrack {
            get {
                return ResourceManager.GetString("hasExternalAudioTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别到外挂字幕轨道.
        /// </summary>
        public static string hasExternalSubtitleTrack {
            get {
                return ResourceManager.GetString("hasExternalSubtitleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定Baseurl.
        /// </summary>
        public static string Help_baseUrl {
            get {
                return ResourceManager.GetString("Help_baseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭混流中的日期写入.
        /// </summary>
        public static string Help_disableDateInfo {
            get {
                return ResourceManager.GetString("Help_disableDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不检测分片数量是否完整.
        /// </summary>
        public static string Help_disableIntegrityCheck {
            get {
                return ResourceManager.GetString("Help_disableIntegrityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅下载视频的一部分分片或长度.
        /// </summary>
        public static string Help_downloadRange {
            get {
                return ResourceManager.GetString("Help_downloadRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early End Percentage of M3U8 files, and skip downloading them if failed for the first time;.
        /// </summary>
        public static string Help_earlyEndPct {
            get {
                return ResourceManager.GetString("Help_earlyEndPct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并时仅封装音频轨道.
        /// </summary>
        public static string Help_enableAudioOnly {
            get {
                return ResourceManager.GetString("Help_enableAudioOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启二进制合并分片.
        /// </summary>
        public static string Help_enableBinaryMerge {
            get {
                return ResourceManager.GetString("Help_enableBinaryMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启下载后删除临时文件夹的功能.
        /// </summary>
        public static string Help_enableDelAfterDone {
            get {
                return ResourceManager.GetString("Help_enableDelAfterDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启混流mp4的FastStart特性.
        /// </summary>
        public static string Help_enableMuxFastStart {
            get {
                return ResourceManager.GetString("Help_enableMuxFastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开启仅解析模式(程序只进行到meta.json).
        /// </summary>
        public static string Help_enableParseOnly {
            get {
                return ResourceManager.GetString("Help_enableParseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定请求头，格式 key:value 使用|分割不同的key&amp;value.
        /// </summary>
        public static string Help_headers {
            get {
                return ResourceManager.GetString("Help_headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接或文件.
        /// </summary>
        public static string Help_input {
            get {
                return ResourceManager.GetString("Help_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直播录制时，达到此长度自动退出软件(HH:MM:SS).
        /// </summary>
        public static string Help_liveRecDur {
            get {
                return ResourceManager.GetString("Help_liveRecDur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置下载速度上限(单位为KB/s).
        /// </summary>
        public static string Help_maxSpeed {
            get {
                return ResourceManager.GetString("Help_maxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定程序的最大线程数.
        /// </summary>
        public static string Help_maxThreads {
            get {
                return ResourceManager.GetString("Help_maxThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only do Merge, NO download!.
        /// </summary>
        public static string Help_mergeOnly {
            get {
                return ResourceManager.GetString("Help_mergeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定程序的最小线程数.
        /// </summary>
        public static string Help_minThreads {
            get {
                return ResourceManager.GetString("Help_minThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用外部json文件定义混流选项.
        /// </summary>
        public static string Help_muxSetJson {
            get {
                return ResourceManager.GetString("Help_muxSetJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用自动合并.
        /// </summary>
        public static string Help_noMerge {
            get {
                return ResourceManager.GetString("Help_noMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不自动使用系统代理.
        /// </summary>
        public static string Help_noProxy {
            get {
                return ResourceManager.GetString("Help_noProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置HTTP/SOCKS5代理, 如 http://127.0.0.1:8080.
        /// </summary>
        public static string Help_proxyAddress {
            get {
                return ResourceManager.GetString("Help_proxyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册m3u8dl链接协议.
        /// </summary>
        public static string Help_registerUrlProtocol {
            get {
                return ResourceManager.GetString("Help_registerUrlProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定程序的重试次数.
        /// </summary>
        public static string Help_retryCount {
            get {
                return ResourceManager.GetString("Help_retryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定存储文件/目录名(不包括后缀).
        /// </summary>
        public static string Help_saveName {
            get {
                return ResourceManager.GetString("Help_saveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当速度低于此值时，重试(单位为KB/s).
        /// </summary>
        public static string Help_stopSpeed {
            get {
                return ResourceManager.GetString("Help_stopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定程序网络请求的超时时间(单位为秒).
        /// </summary>
        public static string Help_timeOut {
            get {
                return ResourceManager.GetString("Help_timeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消注册m3u8dl链接协议.
        /// </summary>
        public static string Help_unregisterUrlProtocol {
            get {
                return ResourceManager.GetString("Help_unregisterUrlProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用Base64字符串定义AES-128解密KEY.
        /// </summary>
        public static string Help_useKeyBase64 {
            get {
                return ResourceManager.GetString("Help_useKeyBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用外部16字节文件定义AES-128解密KEY.
        /// </summary>
        public static string Help_useKeyFile {
            get {
                return ResourceManager.GetString("Help_useKeyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用HEX字符串定义AES-128解密IV.
        /// </summary>
        public static string Help_useKeyIV {
            get {
                return ResourceManager.GetString("Help_useKeyIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定程序工作目录.
        /// </summary>
        public static string Help_workDir {
            get {
                return ResourceManager.GetString("Help_workDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的m3u8.
        /// </summary>
        public static string invalidM3u8 {
            get {
                return ResourceManager.GetString("invalidM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址无效.
        /// </summary>
        public static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别为直播流, 开始录制....
        /// </summary>
        public static string liveStreamFoundAndRecoding {
            get {
                return ResourceManager.GetString("liveStreamFoundAndRecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 识别到大师列表.
        /// </summary>
        public static string masterListFound {
            get {
                return ResourceManager.GetString("masterListFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到更新，版本：{0}! 新版下载成功，请您自行替换.
        /// </summary>
        public static string newerVerisonDownloaded {
            get {
                return ResourceManager.GetString("newerVerisonDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到更新，版本：{0}! 新版下载失败，请您自行下载.
        /// </summary>
        public static string newerVerisonDownloadFailed {
            get {
                return ResourceManager.GetString("newerVerisonDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到更新，版本：{0}! 正在尝试自动下载新版.
        /// </summary>
        public static string newerVisionDetected {
            get {
                return ResourceManager.GetString("newerVisionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持{0}加密方式,将不被处理,且强制开启二进制合并.
        /// </summary>
        public static string notSupportMethod {
            get {
                return ResourceManager.GetString("notSupportMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析m3u8成功, 程序退出.
        /// </summary>
        public static string parseExit {
            get {
                return ResourceManager.GetString("parseExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析m3u8内容.
        /// </summary>
        public static string parsingM3u8 {
            get {
                return ResourceManager.GetString("parsingM3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分片大于1800个，执行分部合并中....
        /// </summary>
        public static string partialMergingPleaseWait {
            get {
                return ResourceManager.GetString("partialMergingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按任意键退出..
        /// </summary>
        public static string pressAnyKeyExit {
            get {
                return ResourceManager.GetString("pressAnyKeyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取文件信息....
        /// </summary>
        public static string readingFileInfo {
            get {
                return ResourceManager.GetString("readingFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录制已到达限定长度.
        /// </summary>
        public static string recordLimitReached {
            get {
                return ResourceManager.GetString("recordLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册m3u8dl链接协议失败！.
        /// </summary>
        public static string registerUrlProtocolFailed {
            get {
                return ResourceManager.GetString("registerUrlProtocolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册m3u8dl链接协议成功！.
        /// </summary>
        public static string registerUrlProtocolSuccessful {
            get {
                return ResourceManager.GetString("registerUrlProtocolSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将文件转换到 MPEG-TS 封装：.
        /// </summary>
        public static string remuxToMPEGTS {
            get {
                return ResourceManager.GetString("remuxToMPEGTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试次数 .
        /// </summary>
        public static string retryCount {
            get {
                return ResourceManager.GetString("retryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储路径：.
        /// </summary>
        public static string savePath {
            get {
                return ResourceManager.GetString("savePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总分片：.
        /// </summary>
        public static string segCount {
            get {
                return ResourceManager.GetString("segCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择分片：.
        /// </summary>
        public static string selectedCount {
            get {
                return ResourceManager.GetString("selectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已自动选择最高清晰度.
        /// </summary>
        public static string selectPlaylist {
            get {
                return ResourceManager.GetString("selectPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遇到了某些错误!.
        /// </summary>
        public static string SomethingWasWrong {
            get {
                return ResourceManager.GetString("SomethingWasWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始下载文件.
        /// </summary>
        public static string startDownloading {
            get {
                return ResourceManager.GetString("startDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始合并分片....
        /// </summary>
        public static string startMerging {
            get {
                return ResourceManager.GetString("startMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始解析 .
        /// </summary>
        public static string startParsing {
            get {
                return ResourceManager.GetString("startParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始解析MPD内容....
        /// </summary>
        public static string startParsingMpd {
            get {
                return ResourceManager.GetString("startParsingMpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新解析m3u8....
        /// </summary>
        public static string startReParsing {
            get {
                return ResourceManager.GetString("startReParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任务结束.
        /// </summary>
        public static string taskDone {
            get {
                return ResourceManager.GetString("taskDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消注册m3u8dl链接协议失败！.
        /// </summary>
        public static string unregisterUrlProtocolFailed {
            get {
                return ResourceManager.GetString("unregisterUrlProtocolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消注册m3u8dl链接协议成功！.
        /// </summary>
        public static string unregisterUrlProtocolSuccessful {
            get {
                return ResourceManager.GetString("unregisterUrlProtocolSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等待下载完成....
        /// </summary>
        public static string waitForCompletion {
            get {
                return ResourceManager.GetString("waitForCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写出playLists.json.
        /// </summary>
        public static string wrtingMasterMeta {
            get {
                return ResourceManager.GetString("wrtingMasterMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 写出meta.json.
        /// </summary>
        public static string wrtingMeta {
            get {
                return ResourceManager.GetString("wrtingMeta", resourceCulture);
            }
        }
    }
}
